# Generated by Django 4.2.5 on 2023-10-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='raiting',
            new_name='rating',
        ),
    ]
