# Generated by Django 4.2.5 on 2023-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_rename_raiting_product_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="shippingPrice",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
